enum SignatureError {
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  INVALID_KEY = "INVALID_KEY",
  KEY_STORE_ERROR = "KEY_STORE_ERROR",
  NO_SUCH_ALGORITHM = "NO_SUCH_ALGORITHM",
  SIGNATURE_ERROR = "SIGNATURE_ERROR",
  KEY_EXPORT_ERROR = "KEY_EXPORT_ERROR",
  GENERAL_ERROR = "GENERAL_ERROR",
}

export default SignatureError;
