name: CI

on:
  pull_request:
    branches: [main]
  push:

jobs:
  npm_install:
    name: Install NPM packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
  npm_lint:
    name: TypeScript linter check
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - run: npm run lint
  ts_check:
    name: TypeScript compile
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - run: |
          npx tsc -b tsconfig.json
          cd example
          npx tsc -b tsconfig.json
  prebuild_android:
    name: Expo prebuild Android
    runs-on: ubuntu-latest
    needs: [npm_lint, ts_check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: Expo prebuild
        working-directory: ./example
        run: npm run prebuild -- --no-install --platform android
  prebuild_ios:
    name: Expo prebuild iOS
    runs-on: ubuntu-latest
    needs: [npm_lint, ts_check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: Expo prebuild
        working-directory: ./example
        run: npm run prebuild -- --no-install --platform ios
