name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'main' }}

jobs:
  npm_install:
    name: Install NPM packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
  expo_lint:
    name: ESLint check
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - run: npm run lint
  expo_build:
    name: Build Expo module
    runs-on: ubuntu-latest
    needs: [npm_install]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - run: npm run build
  prebuild_android:
    name: Expo prebuild Android
    runs-on: ubuntu-latest
    needs: [expo_lint, expo_build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: Expo prebuild
        working-directory: ./example
        run: npm run prebuild -- --no-install --platform android
  prebuild_ios:
    name: Expo prebuild iOS
    runs-on: ubuntu-latest
    needs: [expo_lint, expo_build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: Expo prebuild
        working-directory: ./example
        run: npm run prebuild -- --no-install --platform ios
